dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock mysqlclient reportlab apprise
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
services:
  - mysql
addons:
  postgresql: "9.6"
script:
  - coverage run --omit=*/tests/* --source=hc manage.py test
after_success: coveralls
cache: pip
