# Generated by Django 1.11.6 on 2018-01-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payments", "0002_subscription_plan_id")]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="address_id",
            field=models.CharField(blank=True, max_length=2),
        )
    ]
