# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-04 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payments", "0004_subscription_send_invoices")]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="plan_name",
            field=models.CharField(blank=True, max_length=50),
        )
    ]
