# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payments", "0005_subscription_plan_name")]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="invoice_email",
            field=models.EmailField(blank=True, max_length=254),
        )
    ]
