# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0006_profile_current_team")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="check_limit",
            field=models.IntegerField(default=20),
        )
    ]
