# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0008_profile_bill_to")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_sms_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile", name="sms_limit", field=models.IntegerField(default=0)
        ),
        migrations.AddField(
            model_name="profile", name="sms_sent", field=models.IntegerField(default=0)
        ),
    ]
