# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170714_1734'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE accounts_profile ALTER COLUMN sms_sent SET DEFAULT 0"),
        migrations.RunSQL("ALTER TABLE accounts_profile ALTER COLUMN sms_limit SET DEFAULT 0")
    ]
