# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0011_profile_sort")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nag_period",
            field=models.DurationField(
                choices=[
                    (datetime.timedelta(0), "Disabled"),
                    (datetime.timedelta(0, 3600), "Hourly"),
                    (datetime.timedelta(1), "Daily"),
                ],
                default=datetime.timedelta(0),
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="next_nag_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
