# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0012_auto_20171014_1002")]

    operations = [
        migrations.RemoveField(model_name="profile", name="team_access_allowed")
    ]
