# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("accounts", "0013_remove_profile_team_access_allowed")]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
