# Generated by Django 2.1.2 on 2018-11-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0015_auto_20181029_1858")]

    operations = [migrations.RemoveField(model_name="profile", name="bill_to")]
