# Generated by Django 2.1.5 on 2019-01-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0020_auto_20190112_1950")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="badge_key",
            field=models.CharField(max_length=150, unique=True),
        )
    ]
