# Generated by Django 2.1.5 on 2019-01-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0022_auto_20190114_0857")]

    operations = [
        migrations.RemoveField(model_name="profile", name="api_key"),
        migrations.RemoveField(model_name="profile", name="api_key_id"),
        migrations.RemoveField(model_name="profile", name="api_key_readonly"),
    ]
