# Generated by Django 2.1.5 on 2019-01-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0023_auto_20190117_1419")]

    operations = [
        migrations.RemoveField(model_name="profile", name="current_team"),
        migrations.RemoveField(model_name="profile", name="team_name"),
    ]
