# Generated by Django 3.0.1 on 2020-03-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_auto_20191119_1346"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="current_project",
        ),
    ]
