# Generated by Django 3.1 on 2020-08-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_auto_20200819_0757"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="rw",
            field=models.BooleanField(default=True),
        ),
    ]
