# Generated by Django 3.2.2 on 2021-05-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_credential"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reports",
            field=models.CharField(
                choices=[("off", "Off"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                default="monthly",
                max_length=10,
            ),
        ),
    ]
