# Generated by Django 3.2.2 on 2021-05-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_fill_profile_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tz",
            field=models.CharField(default="UTC", max_length=36),
        ),
    ]
