# Generated by Django 3.2.4 on 2021-06-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_profile_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="reports_allowed",
        ),
    ]
