# Generated by Django 3.2.4 on 2021-07-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_fill_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="rw",
        ),
    ]
