# Generated by Django 3.2.4 on 2021-07-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_add_role_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="totp",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="totp_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
