# Generated by Django 4.2 on 2023-04-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_auto_20210908_1257"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="deletion_scheduled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
