# Generated by Django 4.2.2 on 2023-06-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_profile_deletion_scheduled_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="over_limit_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
