# Generated by Django 5.2.1 on 2025-05-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_convert_email_lowercase"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="default_timezone_selection",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not set"),
                    ("utc", "UTC"),
                    ("check", "Check's time zone"),
                    ("browser", "Browser's time zone"),
                ],
                help_text="Default time zone selection for event logs",
                max_length=20,
                null=True,
            ),
        ),
    ]
