# Generated by Django 5.2.6 on 2025-09-18 12:39
from typing import Any

from django.apps.registry import Apps
from django.db import migrations
from hc.lib.tz import legacy_timezones


def fix_tz(apps: Apps, schema_editor: Any) -> None:
    Profile = apps.get_model("accounts", "Profile")
    for old, new in legacy_timezones.items():
        Profile.objects.filter(tz=old).update(tz=new)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0049_convert_email_lowercase"),
    ]

    operations = [migrations.RunPython(fix_tz, migrations.RunPython.noop)]
