# Generated by Django 5.2.8 on 2025-11-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0050_fix_legacy_timezones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="reports",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="monthly",
                max_length=10,
            ),
        ),
    ]
