# Generated by Django 5.2.1 on 2025-05-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_add_default_timezone_selection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="default_timezone_selection",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("utc", "UTC"),
                    ("check", "Check's time zone"),
                    ("browser", "Browser's time zone"),
                ],
                default="default",
                help_text="Default time zone selection for event logs",
                max_length=20,
            ),
        ),
    ]
