# Generated by Django 6.0.2 on 2026-02-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_alter_profile_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='team_limit',
        ),
    ]
