# Generated by Django 6.0.7 on 2026-07-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_remove_profile_team_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sms_limit',
            field=models.IntegerField(default=0),
        ),
    ]
