# Generated by Django 5.2.1 on 2025-05-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_update_default_timezone_selection_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="browser_timezone_override",
            field=models.CharField(
                blank=True,
                help_text="Override browser time zone detection with a specific time zone",
                max_length=50,
            ),
        ),
    ]
