# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_check_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='n_pings',
            field=models.IntegerField(default=0),
        ),
    ]
