# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_check_n_pings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='n_pings',
        ),
    ]
