# Generated by Django 1.9 on 2016-01-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0021_ping_n")]

    operations = [
        migrations.RemoveField(model_name="notification", name="status"),
        migrations.AddField(
            model_name="notification",
            name="error",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
