# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0023_auto_20160131_1919")]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="kind",
            field=models.CharField(
                choices=[
                    (b"email", b"Email"),
                    (b"webhook", b"Webhook"),
                    (b"hipchat", b"HipChat"),
                    (b"slack", b"Slack"),
                    (b"pd", b"PagerDuty"),
                    (b"po", b"Pushover"),
                    (b"victorops", b"VictorOps"),
                ],
                max_length=20,
            ),
        )
    ]
