# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20160216_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
