# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("api", "0028_auto_20170305_1907")]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        )
    ]
