# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0030_check_last_ping_body")]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="last_ping_body",
            field=models.CharField(blank=True, max_length=10000),
        )
    ]
