# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0035_auto_20171229_2008")]

    operations = [migrations.AlterIndexTogether(name="check", index_together=set([]))]
