# Generated by Django 1.11.6 on 2018-01-16 22:43
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("api", "0035_auto_20171229_2008")]
    # This migration used to remove an index that was
    # added in migration 0015. That migration is now no-op,
    # so this one is too.
    operations = []
