# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-18 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0038_auto_20180318_1306")]

    operations = [migrations.RemoveField(model_name="check", name="last_ping_body")]
