# Generated by Django 2.1 on 2018-08-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0040_auto_20180517_1336")]

    operations = [
        migrations.AddField(
            model_name="check", name="desc", field=models.TextField(blank=True)
        )
    ]
