# Generated by Django 2.1.4 on 2018-12-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0045_flip")]

    operations = [
        migrations.AddField(
            model_name="check",
            name="last_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ping",
            name="start",
            field=models.NullBooleanField(default=False),
        ),
    ]
