# Generated by Django 2.1.4 on 2018-12-25 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("api", "0046_auto_20181218_1245")]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        )
    ]
