# Generated by Django 2.1.4 on 2019-01-02 07:37

from __future__ import annotations

from typing import Any

from django.apps.registry import Apps
from django.db import migrations


def remove_anon_checks(apps: Apps, schema_editor: Any) -> None:
    Check = apps.get_model("api", "Check")
    Check.objects.filter(user=None).delete()


class Migration(migrations.Migration):
    dependencies = [("api", "0047_auto_20181225_2315")]

    operations = [migrations.RunPython(remove_anon_checks, migrations.RunPython.noop)]
