# Generated by Django 2.1.4 on 2019-01-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0051_auto_20190104_0908")]

    operations = [
        migrations.RemoveField(model_name="ping", name="fail"),
        migrations.RemoveField(model_name="ping", name="start"),
    ]
