# Generated by Django 2.1.4 on 2019-01-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0052_auto_20190104_1122")]

    operations = [
        migrations.AddField(
            model_name="check",
            name="subject",
            field=models.CharField(blank=True, max_length=100),
        )
    ]
