# Generated by Django 2.1.5 on 2019-01-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0056_auto_20190114_0857")]

    operations = [
        migrations.RemoveField(model_name="channel", name="user"),
        migrations.RemoveField(model_name="check", name="user"),
    ]
