# Generated by Django 2.2 on 2019-04-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0059_auto_20190314_1744")]

    operations = [
        migrations.CreateModel(
            name="TokenBucket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=80, unique=True)),
                ("tokens", models.FloatField(default=1.0)),
                ("updated", models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
