# Generated by Django 2.2.3 on 2019-07-20 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_webhook_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="kind",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("webhook", "Webhook"),
                    ("hipchat", "HipChat"),
                    ("slack", "Slack"),
                    ("pd", "PagerDuty"),
                    ("pagertree", "PagerTree"),
                    ("pagerteam", "Pager Team"),
                    ("po", "Pushover"),
                    ("pushbullet", "Pushbullet"),
                    ("opsgenie", "OpsGenie"),
                    ("victorops", "VictorOps"),
                    ("discord", "Discord"),
                    ("telegram", "Telegram"),
                    ("sms", "SMS"),
                    ("zendesk", "Zendesk"),
                    ("trello", "Trello"),
                    ("matrix", "Matrix"),
                    ("whatsapp", "WhatsApp"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="flip",
            name="processed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tokenbucket",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name="check",
            index=models.Index(
                condition=models.Q(_negated=True, status="down"),
                fields=["alert_after"],
                name="api_check_aa_not_down",
            ),
        ),
        migrations.AddIndex(
            model_name="flip",
            index=models.Index(
                condition=models.Q(processed=None),
                fields=["processed"],
                name="api_flip_not_processed",
            ),
        ),
    ]
