# Generated by Django 3.0.1 on 2020-01-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_auto_20191127_1240"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="last_error",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
