# Generated by Django 3.0.1 on 2020-01-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_last_error_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ping",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
