# Generated by Django 3.0.1 on 2020-01-17 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0068_auto_20200117_1023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ping",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
