# Generated by Django 3.0.4 on 2020-05-28 03:20

from django.db import migrations, models
from hc.api.models import Check

def generate_unique_keys(apps, schema_editor):
    for o in Check.objects.all():
        o.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20200411_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='unique_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.RunPython(generate_unique_keys),
    ]
