# Generated by Django 3.0.8 on 2020-07-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0072_auto_20200701_1007"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="subject_fail",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="channel",
            name="kind",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("webhook", "Webhook"),
                    ("hipchat", "HipChat"),
                    ("slack", "Slack"),
                    ("pd", "PagerDuty"),
                    ("pagertree", "PagerTree"),
                    ("pagerteam", "Pager Team"),
                    ("po", "Pushover"),
                    ("pushbullet", "Pushbullet"),
                    ("opsgenie", "OpsGenie"),
                    ("victorops", "VictorOps"),
                    ("discord", "Discord"),
                    ("telegram", "Telegram"),
                    ("sms", "SMS"),
                    ("zendesk", "Zendesk"),
                    ("trello", "Trello"),
                    ("matrix", "Matrix"),
                    ("whatsapp", "WhatsApp"),
                    ("apprise", "Apprise"),
                    ("mattermost", "Mattermost"),
                    ("msteams", "Microsoft Teams"),
                    ("shell", "Shell Command"),
                    ("zulip", "Zulip"),
                    ("spike", "Spike"),
                ],
                max_length=20,
            ),
        ),
    ]
