# Generated by Django 3.1 on 2020-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_auto_20200803_1411"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="last_ping_was_fail",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="check",
            name="manual_resume",
            field=models.BooleanField(default=False),
        ),
    ]
