# Generated by Django 3.2.8 on 2021-10-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0080_fill_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="last_notify",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
