# Generated by Django 3.2.10 on 2022-01-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0082_fill_last_notify"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="disabled",
            field=models.BooleanField(null=True),
        ),
    ]
