# Generated by Django 4.0.2 on 2022-02-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0083_channel_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="ping",
            name="body_raw",
            field=models.BinaryField(null=True),
        ),
    ]
