# Generated by Django 4.0.6 on 2022-07-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0089_remove_check_subject_remove_check_subject_fail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="filter_subject",
            field=models.BooleanField(default=False),
        ),
    ]
