# Generated by Django 4.0.6 on 2022-07-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0091_alter_check_filter_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="success_kw",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
    ]
