# Generated by Django 4.1.2 on 2022-11-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_ping_rid_alter_channel_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='rid',
            field=models.UUIDField(null=True),
        ),
    ]
