# Generated by Django 4.1.2 on 2022-11-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0094_ping_rid_alter_channel_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="last_start_rid",
            field=models.UUIDField(null=True),
        ),
    ]
