# Generated by Django 4.1.2 on 2022-11-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_alter_ping_rid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='rid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
