# Generated by Django 4.2.4 on 2023-08-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0098_channel_last_notify_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
    ]
