# Generated by Django 5.0.2 on 2024-02-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0102_alter_check_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="badge_key",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
