# Generated by Django 5.0.4 on 2024-05-17 07:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0103_check_badge_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
