# Generated by Django 5.0.4 on 2024-04-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_check_badge_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='body_truncate_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='body_truncate_length',
            field=models.IntegerField(default=1000),
        ),
    ]
