# Generated by Django 5.0.4 on 2024-06-13 11:58

from __future__ import annotations

from typing import Any

from django.apps.registry import Apps
from django.db import migrations


def fix_tz(apps: Apps, schema_editor: Any) -> None:
    Check = apps.get_model("api", "Check")
    Check.objects.filter(tz="Europe/Kiev").update(tz="Europe/Kyiv")


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0105_alter_notification_code"),
    ]

    operations = [migrations.RunPython(fix_tz, migrations.RunPython.noop)]
