# Generated by Django 5.1.3 on 2024-11-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_alter_channel_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='flip',
            name='reason',
            field=models.CharField(choices=[('', 'Unknown'), ('timeout', 'Timeout'), ('fail', 'Fail signal')], default='', max_length=8),
        ),
    ]
