# Generated by Django 5.1.3 on 2024-12-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_flip_reason'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flip',
            index=models.Index(fields=['owner', 'created'], name='api_flip_owner_created'),
        ),
    ]
