# Generated by Django 5.1.7 on 2025-04-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_alter_check_badge_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='failure_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated list of failure keywords.'),
        ),
        migrations.AddField(
            model_name='check',
            name='success_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated list of success keywords.'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('apprise', 'Apprise'), ('call', 'Phone Call'), ('discord', 'Discord'), ('email', 'Email'), ('github', 'GitHub'), ('gotify', 'Gotify'), ('group', 'Group'), ('linenotify', 'LINE Notify (stops working Apr 2025)'), ('matrix', 'Matrix'), ('mattermost', 'Mattermost'), ('msteams', 'MS Teams Connector (stops working Jan 2025)'), ('msteamsw', 'Microsoft Teams'), ('ntfy', 'ntfy'), ('opsgenie', 'Opsgenie'), ('pagertree', 'PagerTree'), ('pd', 'PagerDuty'), ('po', 'Pushover'), ('pushbullet', 'Pushbullet'), ('rocketchat', 'Rocket.Chat'), ('shell', 'Shell Command'), ('signal', 'Signal'), ('slack', 'Slack'), ('sms', 'SMS'), ('spike', 'Spike'), ('telegram', 'Telegram'), ('trello', 'Trello'), ('victorops', 'Splunk On-Call'), ('webhook', 'Webhook'), ('whatsapp', 'WhatsApp'), ('zulip', 'Zulip')], max_length=20),
        ),
    ]
