# Generated by Django 5.2.8 on 2025-11-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0118_alter_check_badge_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="filter_default_fail",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="check",
            name="filter_http_body",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="channel",
            name="kind",
            field=models.CharField(
                choices=[
                    ("apprise", "Apprise"),
                    ("call", "Phone Call"),
                    ("discord", "Discord"),
                    ("email", "Email"),
                    ("github", "GitHub"),
                    ("googlechat", "Google Chat"),
                    ("gotify", "Gotify"),
                    ("group", "Group"),
                    ("linenotify", "LINE Notify (stops working Apr 2025)"),
                    ("matrix", "Matrix"),
                    ("mattermost", "Mattermost"),
                    ("msteams", "MS Teams Connector (stops working Jan 2025)"),
                    ("msteamsw", "Microsoft Teams"),
                    ("ntfy", "ntfy"),
                    ("opsgenie", "Opsgenie"),
                    ("pagertree", "PagerTree"),
                    ("pd", "PagerDuty"),
                    ("po", "Pushover"),
                    ("pushbullet", "Pushbullet"),
                    ("rocketchat", "Rocket.Chat"),
                    ("shell", "Shell Command"),
                    ("signal", "Signal"),
                    ("slack", "Slack"),
                    ("sms", "SMS"),
                    ("spike", "Spike"),
                    ("telegram", "Telegram"),
                    ("trello", "Trello"),
                    ("victorops", "Splunk On-Call"),
                    ("webhook", "Webhook"),
                    ("whatsapp", "WhatsApp"),
                    ("zulip", "Zulip"),
                ],
                max_length=20,
            ),
        ),
    ]
