# Generated by Django 6.0 on 2025-12-16 12:55

from typing import Any

from django.apps.registry import Apps
from django.db import migrations


def fix_ping_kind(apps: Apps, schema_editor: Any) -> None:
    Ping = apps.get_model("api", "Ping")
    Ping.objects.filter(kind="").update(kind=None)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0119_check_filter_default_fail_check_filter_http_body_and_more"),
    ]

    operations = [migrations.RunPython(fix_ping_kind, migrations.RunPython.noop)]
