# Generated by Django 5.1.8 on 2025-04-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_check_failure_keywords_check_success_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='req_failure_kw',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='check',
            name='req_start_kw',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='check',
            name='req_success_kw',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
