# Generated by Django 6.0 on 2026-01-07 10:18

from __future__ import annotations

from typing import Any

from django.apps.registry import Apps
from django.db import migrations

from hc.lib.tz import legacy_timezones


def fix_tz(apps: Apps, schema_editor: Any) -> None:
    Check = apps.get_model("api", "Check")
    for old, new in legacy_timezones.items():
        Check.objects.filter(tz=old).update(tz=new)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0120_fix_ping_kind"),
    ]

    operations = [migrations.RunPython(fix_tz, migrations.RunPython.noop)]
