# Generated by Django 6.0.1 on 2026-01-12 12:26

from typing import Any

from django.apps.registry import Apps
from django.db import migrations


def delete_channels(apps: Apps, schema_editor: Any) -> None:
    Channel = apps.get_model("api", "Channel")
    Channel.objects.filter(kind="msteams").delete()
    Channel.objects.filter(kind="linenotify").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0121_fix_legacy_timezones_ii"),
    ]

    operations = [migrations.RunPython(delete_channels, migrations.RunPython.noop)]
