# Generated by Django 5.2 on 2025-04-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_merge_20250425_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='max_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='check',
            name='min_duration',
            field=models.IntegerField(default=0),
        ),
    ]
