# Generated by Django 5.2 on 2025-04-30 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_merge_20250425_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='max_duration',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='min_duration',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AddField(
            model_name='ping',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flip',
            name='reason',
            field=models.CharField(choices=[('', 'Unknown'), ('timeout', 'Timeout'), ('fail', 'Fail signal'), ('duration', 'Duration out of bounds')], default='', max_length=8),
        ),
    ]
