# Generated by Django 5.2 on 2025-05-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_check_max_duration_check_min_duration_ping_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
