# Generated by Django 6.0.2 on 2026-02-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_delete_msteams_linenotify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('apprise', 'Apprise'), ('call', 'Phone Call'), ('discord', 'Discord'), ('email', 'Email'), ('github', 'GitHub'), ('googlechat', 'Google Chat'), ('gotify', 'Gotify'), ('group', 'Group'), ('matrix', 'Matrix'), ('mattermost', 'Mattermost'), ('msteamsw', 'Microsoft Teams'), ('ntfy', 'ntfy'), ('opsgenie', 'Opsgenie'), ('pagertree', 'PagerTree'), ('pd', 'PagerDuty'), ('po', 'Pushover'), ('pushbullet', 'Pushbullet'), ('rocketchat', 'Rocket.Chat'), ('shell', 'Shell Command'), ('signal', 'Signal'), ('slack', 'Slack'), ('sms', 'SMS'), ('spike', 'Spike'), ('telegram', 'Telegram'), ('trello', 'Trello'), ('victorops', 'Splunk On-Call'), ('webhook', 'Webhook'), ('whatsapp', 'WhatsApp'), ('zulip', 'Zulip')], max_length=20),
        ),
    ]
