# Generated by Django 5.2 on 2025-04-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_check_max_duration_check_min_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='max_duration',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='min_duration',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
