# Generated by Django 5.2 on 2025-04-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0123_alter_check_max_duration_alter_check_min_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="ping",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
