# Generated by Django 5.2 on 2025-04-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_alter_check_max_duration_alter_check_min_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='max_duration',
            field=models.DurationField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='min_duration',
            field=models.DurationField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='flip',
            name='reason',
            field=models.CharField(choices=[('', 'Unknown'), ('timeout', 'Timeout'), ('fail', 'Fail signal'), ('duration', 'Duration out of bounds')], default='', max_length=8),
        ),
    ]
