# Generated by Django 5.2 on 2025-04-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_alter_check_max_duration_alter_check_min_duration_and_more'),
        ('api', '0124_ping_duration'),
    ]

    operations = [
    ]
