# Generated by Django 5.2 on 2025-04-30 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_merge_20250430_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='max_duration',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='min_duration',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
    ]
