# Generated by Django 5.2 on 2025-04-30 13:21

from django.db import migrations, models
from django.db import connection


def convert_durations(apps, schema_editor):
    """Convert integer durations to timedelta objects."""
    Check = apps.get_model('api', 'Check')
    
    for check in Check.objects.all():
        if check.min_duration is not None:
            if not hasattr(check.min_duration, 'total_seconds'):
                from datetime import timedelta
                check.min_duration = timedelta(seconds=check.min_duration)
        
        if check.max_duration is not None:
            if not hasattr(check.max_duration, 'total_seconds'):
                from datetime import timedelta
                check.max_duration = timedelta(seconds=check.max_duration)
        
        check.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_alter_check_max_duration_alter_check_min_duration'),
    ]

    operations = [
        migrations.RunPython(
            convert_durations,
            reverse_code=migrations.RunPython.noop
        ),
    ]
