# Generated by Django 4.2.6 on 2023-10-31 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "notset"),
                            (10, "debug"),
                            (20, "info"),
                            (30, "warning"),
                            (40, "error"),
                            (50, "critical"),
                        ]
                    ),
                ),
                ("message", models.TextField()),
                ("traceback", models.TextField()),
            ],
        ),
    ]
