# Generated by Django 5.0.4 on 2024-05-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="host",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
